kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: taskflowProj
  namespace: argocd

spec:
  description: "This is Project for TASKFLOW argocd"
  sourceRepos:
    - '{TASKFLOW-DEPLOY REPO}'
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: taskflow 