kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: task-service-hpa
  namespace: taskflow

spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: task_service
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 70