kind: Deployment
apiVersion: apps/v1 
metadata:
  name: notification
  namespace: taskflow

spec:
  selector:
    matchLabels:
      app: notification

  template:
    metadata:
      labels: 
        app: notification

    spec:
      containers:
        - name: notification
          image: shivam1481/taskflow-python:6
          args: ["notification_service.worker"]

          env:
            - name: IDENTITY_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: IDENTITY_DB_DSN
          envFrom:
            - configMapRef:
                name: python-env

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "200m"
              memory: "256Mi"
