apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: taskflow
spec:
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: shivam1481/identity-service:v1
          ports:
            - containerPort: 8081
          env: 
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: SPRING_DATASOURCE_PASSWORD
          envFrom:
            - configMapRef:
                name: identity-java-env
          volumeMounts:
            - name: jwt-key-volume
              mountPath: /etc/secrets/jwt
              readOnly: true
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
      volumes:
        - name: jwt-key-volume
          secret:
            secretName: jwt-key-secret
    ## Run this command before applying deployment 
    ## kubectl create secret generic jwt-key-secret \
    ## --namespace=taskflow \
    ## --from-file=jwt-private.pem=./path/to/your/actual-key-file.pem