kind: Deployment
apiVersion: apps/v1
metadata:
  name: outbox
  namespace: taskflow

spec:
  selector:
    matchLabels:
      app: outbox
  
  template:
    metadata:
      labels:
        app: outbox

    spec:
      containers:
        - name: outbox
          image: shivam1481/taskflow-python:6

          env:
            - name: IDENTITY_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: IDENTITY_DB_DSN
            - name: TASKS_DB_DSN
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: TASKS_DB_DSN

          envFrom:
            - configMapRef:
                name: python-env

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            
            limits:
              cpu: "200m"
              memory: "256Mi"